# Generated by Django 5.2.4 on 2025-08-06 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="is_payd",
            field=models.BooleanField(default=False, verbose_name="Оплачен"),
        ),
    ]
