# Generated by Django 5.2.4 on 2025-08-06 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_order_is_payd"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="is_payd",
            new_name="is_paid",
        ),
    ]
